ARG IMAGE_VERSION

FROM python:$IMAGE_VERSION

WORKDIR /usr/src/app

COPY api/requirements.txt ./

RUN pip install -U pip

RUN pip install --no-cache-dir -r ./requirements.txt

COPY . .

ENV FLASK_APP=api/app.py

CMD flask run --host=0.0.0.0